services:
  jekyll:
    build: .
    command: jekyll build --watch
    tty: true
    volumes:
      - ./app:/srv/jekyll
      - /srv/jekyll/node_modules
      - ./build:/srv/build
      - ./bundle:/usr/local/bundle:delegated
  server:
    image: nginx:1.14.2
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
